// <auto-generated />
namespace MissingLinkPro.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class PackageStatementDesc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PackageStatementDesc));
        
        string IMigrationMetadata.Id
        {
            get { return "201411111625341_PackageStatementDesc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
