//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace LendingTreeLib.Schemas
{
    using System;
    using System.IO;
    using System.Xml.Linq;
    using System.Xml.Serialization;

    public partial class LendingTreeAffiliateRequest
    {
        public LendingTreeAffiliateRequest()
        {
            this.Request = new RequestType();
        }

        public override string ToString()
        {
            try
            {
                var serializer = new XmlSerializer(this.GetType());
                string utf8;
                using (StringWriter writer = new LendingTreeLib.Common.Utf8StringWriter())
                {
                    serializer.Serialize(writer, this);
                    utf8 = writer.ToString();
                }
                return utf8;
            }
            catch (System.Exception ex)
            {
                return ex.Message;
            }
        }

        internal static void Create(XElement xe, out LendingTreeAffiliateRequest o)
        {
            var serializer = new XmlSerializer(typeof(LendingTreeAffiliateRequest));
            o = (LendingTreeAffiliateRequest)serializer.Deserialize(xe.CreateReader());
        }
    }


    public partial class RequestType
    {
        public RequestType()
        {
            AppID = Guid.Empty.ToString();

            HomeLoanProduct = new HomeLoanProductType();

            Applicant = new ApplicantType[1];
            Applicant[0] = new ApplicantType();

            RequestType rt = this;
            rt.type = "Refinance";
            rt.created = string.Format("{0:yyyy-MM-dd HH:mm:ss}", DateTime.Now);
            rt.updated = string.Format("{0:yyyy-MM-dd HH:mm:ss}", DateTime.Now);
            rt.VisitorSessionID = "0";
            rt.ElectronicDisclosureConsent = "Y";

            ApplicantType at = Applicant[0];
            at.Password = "1234";
            at.RelationshipToApplicant = RelationshipToApplicantType.SELF;
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ApplicantType TheApplicant
        {
            get
            {
                return Applicant[0];
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ELoanType LoanType
        {
            get
            {
                try
                {
                    if (HomeLoanProduct.Item is RefinanceType) return ELoanType.REFINANCE;
                    else if (HomeLoanProduct.Item is PurchaseType) return ELoanType.PURCHASE;
                    else throw new Exception("invalid LoanType");
                }
                catch (Exception)
                {
                    throw new Exception("error getting LoanType - never set?");
                }
            }
            set
            {
                switch (value)
                {
                    case ELoanType.REFINANCE:
                        this.type = "Refinance";
                        HomeLoanProduct.Item = new RefinanceType();
                        // TEST TEMP TREE.com will FIX
                        RefinanceType rt = HomeLoanProduct.Item as RefinanceType;
                        rt.RequestedProducts = new[] { ProductType.Item30YRF, ProductType.Item15YRF, ProductType.Item5YRARM };
                        break;
                    case ELoanType.PURCHASE:
                        this.type = "Purchase";
                        HomeLoanProduct.Item = new PurchaseType();
                        break;
                    default:
                        break;
                }
            }
        }
    }

    public enum ELoanType
    {
        REFINANCE,
        PURCHASE
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class LendingTreeAffiliateRequest : object, System.ComponentModel.INotifyPropertyChanged
    {

        private RequestType requestField;

        private ResponseType responseField;

        /// <remarks/>
        public RequestType Request
        {
            get
            {
                return this.requestField;
            }
            set
            {
                this.requestField = value;
                this.RaisePropertyChanged("Request");
            }
        }

        /// <remarks/>
        public ResponseType Response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
                this.RaisePropertyChanged("Response");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequestType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private SourceOfRequestType sourceOfRequestField;

        private HomeLoanProductType homeLoanProductField;

        private ApplicantType[] applicantField;

        private string typeField;

        private string createdField;

        private string updatedField;

        private string visitorSessionIDField;

        private string appIDField;

        private string electronicDisclosureConsentField;

        /// <remarks/>
        public SourceOfRequestType SourceOfRequest
        {
            get
            {
                return this.sourceOfRequestField;
            }
            set
            {
                this.sourceOfRequestField = value;
                this.RaisePropertyChanged("SourceOfRequest");
            }
        }

        /// <remarks/>
        public HomeLoanProductType HomeLoanProduct
        {
            get
            {
                return this.homeLoanProductField;
            }
            set
            {
                this.homeLoanProductField = value;
                this.RaisePropertyChanged("HomeLoanProduct");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Applicant")]
        public ApplicantType[] Applicant
        {
            get
            {
                return this.applicantField;
            }
            set
            {
                this.applicantField = value;
                this.RaisePropertyChanged("Applicant");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string created
        {
            get
            {
                return this.createdField;
            }
            set
            {
                this.createdField = value;
                this.RaisePropertyChanged("created");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string updated
        {
            get
            {
                return this.updatedField;
            }
            set
            {
                this.updatedField = value;
                this.RaisePropertyChanged("updated");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string VisitorSessionID
        {
            get
            {
                return this.visitorSessionIDField;
            }
            set
            {
                this.visitorSessionIDField = value;
                this.RaisePropertyChanged("VisitorSessionID");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string AppID
        {
            get
            {
                return this.appIDField;
            }
            set
            {
                this.appIDField = value;
                this.RaisePropertyChanged("AppID");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string ElectronicDisclosureConsent
        {
            get
            {
                return this.electronicDisclosureConsentField;
            }
            set
            {
                this.electronicDisclosureConsentField = value;
                this.RaisePropertyChanged("ElectronicDisclosureConsent");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class SourceOfRequestType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string lendingTreeAffiliatePartnerCodeField;

        private string lendingTreeAffiliateUserNameField;

        private string lendingTreeAffiliatePasswordField;

        private string lendingTreeAffiliateEsourceIDField;

        private string lendingTreeAffiliateBrandField;

        private string lendingTreeAffiliateFormVersionField;

        private string visitorIPAddressField;

        private string visitorURLField;

        private string treeSessionIDField;

        private string treeComputerIDField;

        private string v1stCookieField;

        private YesNoType lTLOptinField;

        /// <remarks/>
        public string LendingTreeAffiliatePartnerCode
        {
            get
            {
                return this.lendingTreeAffiliatePartnerCodeField;
            }
            set
            {
                this.lendingTreeAffiliatePartnerCodeField = value;
                this.RaisePropertyChanged("LendingTreeAffiliatePartnerCode");
            }
        }

        /// <remarks/>
        public string LendingTreeAffiliateUserName
        {
            get
            {
                return this.lendingTreeAffiliateUserNameField;
            }
            set
            {
                this.lendingTreeAffiliateUserNameField = value;
                this.RaisePropertyChanged("LendingTreeAffiliateUserName");
            }
        }

        /// <remarks/>
        public string LendingTreeAffiliatePassword
        {
            get
            {
                return this.lendingTreeAffiliatePasswordField;
            }
            set
            {
                this.lendingTreeAffiliatePasswordField = value;
                this.RaisePropertyChanged("LendingTreeAffiliatePassword");
            }
        }

        /// <remarks/>
        public string LendingTreeAffiliateEsourceID
        {
            get
            {
                return this.lendingTreeAffiliateEsourceIDField;
            }
            set
            {
                this.lendingTreeAffiliateEsourceIDField = value;
                this.RaisePropertyChanged("LendingTreeAffiliateEsourceID");
            }
        }

        /// <remarks/>
        public string LendingTreeAffiliateBrand
        {
            get
            {
                return this.lendingTreeAffiliateBrandField;
            }
            set
            {
                this.lendingTreeAffiliateBrandField = value;
                this.RaisePropertyChanged("LendingTreeAffiliateBrand");
            }
        }

        /// <remarks/>
        public string LendingTreeAffiliateFormVersion
        {
            get
            {
                return this.lendingTreeAffiliateFormVersionField;
            }
            set
            {
                this.lendingTreeAffiliateFormVersionField = value;
                this.RaisePropertyChanged("LendingTreeAffiliateFormVersion");
            }
        }

        /// <remarks/>
        public string VisitorIPAddress
        {
            get
            {
                return this.visitorIPAddressField;
            }
            set
            {
                this.visitorIPAddressField = value;
                this.RaisePropertyChanged("VisitorIPAddress");
            }
        }

        /// <remarks/>
        public string VisitorURL
        {
            get
            {
                return this.visitorURLField;
            }
            set
            {
                this.visitorURLField = value;
                this.RaisePropertyChanged("VisitorURL");
            }
        }

        /// <remarks/>
        public string TreeSessionID
        {
            get
            {
                return this.treeSessionIDField;
            }
            set
            {
                this.treeSessionIDField = value;
                this.RaisePropertyChanged("TreeSessionID");
            }
        }

        /// <remarks/>
        public string TreeComputerID
        {
            get
            {
                return this.treeComputerIDField;
            }
            set
            {
                this.treeComputerIDField = value;
                this.RaisePropertyChanged("TreeComputerID");
            }
        }

        /// <remarks/>
        public string V1stCookie
        {
            get
            {
                return this.v1stCookieField;
            }
            set
            {
                this.v1stCookieField = value;
                this.RaisePropertyChanged("V1stCookie");
            }
        }

        /// <remarks/>
        public YesNoType LTLOptin
        {
            get
            {
                return this.lTLOptinField;
            }
            set
            {
                this.lTLOptinField = value;
                this.RaisePropertyChanged("LTLOptin");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum YesNoType
    {

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ErrorsType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string errorField;

        /// <remarks/>
        public string Error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResponseType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string returnURLField;

        private ErrorsType errorsField;

        /// <remarks/>
        public string ReturnURL
        {
            get
            {
                return this.returnURLField;
            }
            set
            {
                this.returnURLField = value;
                this.RaisePropertyChanged("ReturnURL");
            }
        }

        /// <remarks/>
        public ErrorsType Errors
        {
            get
            {
                return this.errorsField;
            }
            set
            {
                this.errorsField = value;
                this.RaisePropertyChanged("Errors");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreditHistoryType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private CreditHistoryTypeCreditSelfRating creditSelfRatingField;

        private YesNoType declaredBankruptcyField;

        private bool declaredBankruptcyFieldSpecified;

        private YesNoType declaredForeclosureField;

        private bool declaredForeclosureFieldSpecified;

        private CreditHistoryTypeBankruptcyDischarged bankruptcyDischargedField;

        private CreditHistoryTypeForeclosureDischarged foreclosureDischargedField;

        /// <remarks/>
        public CreditHistoryTypeCreditSelfRating CreditSelfRating
        {
            get
            {
                return this.creditSelfRatingField;
            }
            set
            {
                this.creditSelfRatingField = value;
                this.RaisePropertyChanged("CreditSelfRating");
            }
        }

        /// <remarks/>
        public YesNoType DeclaredBankruptcy
        {
            get
            {
                return this.declaredBankruptcyField;
            }
            set
            {
                this.declaredBankruptcyField = value;
                this.RaisePropertyChanged("DeclaredBankruptcy");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeclaredBankruptcySpecified
        {
            get
            {
                return this.declaredBankruptcyFieldSpecified;
            }
            set
            {
                this.declaredBankruptcyFieldSpecified = value;
                this.RaisePropertyChanged("DeclaredBankruptcySpecified");
            }
        }

        /// <remarks/>
        public YesNoType DeclaredForeclosure
        {
            get
            {
                return this.declaredForeclosureField;
            }
            set
            {
                this.declaredForeclosureField = value;
                this.RaisePropertyChanged("DeclaredForeclosure");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeclaredForeclosureSpecified
        {
            get
            {
                return this.declaredForeclosureFieldSpecified;
            }
            set
            {
                this.declaredForeclosureFieldSpecified = value;
                this.RaisePropertyChanged("DeclaredForeclosureSpecified");
            }
        }

        /// <remarks/>
        public CreditHistoryTypeBankruptcyDischarged BankruptcyDischarged
        {
            get
            {
                return this.bankruptcyDischargedField;
            }
            set
            {
                this.bankruptcyDischargedField = value;
                this.RaisePropertyChanged("BankruptcyDischarged");
            }
        }

        /// <remarks/>
        public CreditHistoryTypeForeclosureDischarged ForeclosureDischarged
        {
            get
            {
                return this.foreclosureDischargedField;
            }
            set
            {
                this.foreclosureDischargedField = value;
                this.RaisePropertyChanged("ForeclosureDischarged");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum CreditHistoryTypeCreditSelfRating
    {

        /// <remarks/>
        EXCELLENT,

        /// <remarks/>
        LITTLEORNOCREDITHISTORY,

        /// <remarks/>
        MAJORCREDITPROBLEMS,

        /// <remarks/>
        SOMECREDITPROBLEMS,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum CreditHistoryTypeBankruptcyDischarged
    {

        /// <remarks/>
        NOT_YET_DISCHARGED,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01-12_MONTHS")]
        Item0112_MONTHS,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("13-24_MONTHS")]
        Item1324_MONTHS,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("25-36_MONTHS")]
        Item2536_MONTHS,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("37-48_MONTHS")]
        Item3748_MONTHS,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("49-60_MONTHS")]
        Item4960_MONTHS,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("61-72_MONTHS")]
        Item6172_MONTHS,

        /// <remarks/>
        OVER_72_MONTHS,

        /// <remarks/>
        OVER_84_MONTHS,

        /// <remarks/>
        NEVER,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum CreditHistoryTypeForeclosureDischarged
    {

        /// <remarks/>
        CURRENTLY_IN_FORECLOSURE,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01-12_MONTHS")]
        Item0112_MONTHS,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("13-24_MONTHS")]
        Item1324_MONTHS,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("25-36_MONTHS")]
        Item2536_MONTHS,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("37-48_MONTHS")]
        Item3748_MONTHS,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("49-60_MONTHS")]
        Item4960_MONTHS,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("61-72_MONTHS")]
        Item6172_MONTHS,

        /// <remarks/>
        OVER_72_MONTHS,

        /// <remarks/>
        OVER_84_MONTHS,

        /// <remarks/>
        NEVER,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmploymentType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string employerNameField;

        private string employeeTitleField;

        private string employmentYearsField;

        private EmploymentStausType employmentStatusField;

        private bool employmentStatusFieldSpecified;

        private decimal employmentIncomeField;

        private bool employmentIncomeFieldSpecified;

        private string employmentIndicatorField;

        /// <remarks/>
        public string EmployerName
        {
            get
            {
                return this.employerNameField;
            }
            set
            {
                this.employerNameField = value;
                this.RaisePropertyChanged("EmployerName");
            }
        }

        /// <remarks/>
        public string EmployeeTitle
        {
            get
            {
                return this.employeeTitleField;
            }
            set
            {
                this.employeeTitleField = value;
                this.RaisePropertyChanged("EmployeeTitle");
            }
        }

        /// <remarks/>
        public string EmploymentYears
        {
            get
            {
                return this.employmentYearsField;
            }
            set
            {
                this.employmentYearsField = value;
                this.RaisePropertyChanged("EmploymentYears");
            }
        }

        /// <remarks/>
        public EmploymentStausType EmploymentStatus
        {
            get
            {
                return this.employmentStatusField;
            }
            set
            {
                this.employmentStatusField = value;
                this.RaisePropertyChanged("EmploymentStatus");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EmploymentStatusSpecified
        {
            get
            {
                return this.employmentStatusFieldSpecified;
            }
            set
            {
                this.employmentStatusFieldSpecified = value;
                this.RaisePropertyChanged("EmploymentStatusSpecified");
            }
        }

        /// <remarks/>
        public decimal EmploymentIncome
        {
            get
            {
                return this.employmentIncomeField;
            }
            set
            {
                this.employmentIncomeField = value;
                this.RaisePropertyChanged("EmploymentIncome");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EmploymentIncomeSpecified
        {
            get
            {
                return this.employmentIncomeFieldSpecified;
            }
            set
            {
                this.employmentIncomeFieldSpecified = value;
                this.RaisePropertyChanged("EmploymentIncomeSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string EmploymentIndicator
        {
            get
            {
                return this.employmentIndicatorField;
            }
            set
            {
                this.employmentIndicatorField = value;
                this.RaisePropertyChanged("EmploymentIndicator");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum EmploymentStausType
    {

        /// <remarks/>
        FULLTIME,

        /// <remarks/>
        HOMEMAKER,

        /// <remarks/>
        PARTTIME,

        /// <remarks/>
        RETIRED,

        /// <remarks/>
        SELFEMPLOYED,

        /// <remarks/>
        STUDENT,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContactPreferenceType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private ContactPreferenceTypePreferredContactPlace preferredContactPlaceField;

        private bool preferredContactPlaceFieldSpecified;

        private ContactPreferenceTypePreferredContactMethod preferredContactMethodField;

        private bool preferredContactMethodFieldSpecified;

        private ContactPreferenceTypePreferredContactTime preferredContactTimeField;

        private bool preferredContactTimeFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public ContactPreferenceTypePreferredContactPlace PreferredContactPlace
        {
            get
            {
                return this.preferredContactPlaceField;
            }
            set
            {
                this.preferredContactPlaceField = value;
                this.RaisePropertyChanged("PreferredContactPlace");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PreferredContactPlaceSpecified
        {
            get
            {
                return this.preferredContactPlaceFieldSpecified;
            }
            set
            {
                this.preferredContactPlaceFieldSpecified = value;
                this.RaisePropertyChanged("PreferredContactPlaceSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public ContactPreferenceTypePreferredContactMethod PreferredContactMethod
        {
            get
            {
                return this.preferredContactMethodField;
            }
            set
            {
                this.preferredContactMethodField = value;
                this.RaisePropertyChanged("PreferredContactMethod");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PreferredContactMethodSpecified
        {
            get
            {
                return this.preferredContactMethodFieldSpecified;
            }
            set
            {
                this.preferredContactMethodFieldSpecified = value;
                this.RaisePropertyChanged("PreferredContactMethodSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public ContactPreferenceTypePreferredContactTime PreferredContactTime
        {
            get
            {
                return this.preferredContactTimeField;
            }
            set
            {
                this.preferredContactTimeField = value;
                this.RaisePropertyChanged("PreferredContactTime");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PreferredContactTimeSpecified
        {
            get
            {
                return this.preferredContactTimeFieldSpecified;
            }
            set
            {
                this.preferredContactTimeFieldSpecified = value;
                this.RaisePropertyChanged("PreferredContactTimeSpecified");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum ContactPreferenceTypePreferredContactPlace
    {

        /// <remarks/>
        Home,

        /// <remarks/>
        Work,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum ContactPreferenceTypePreferredContactMethod
    {

        /// <remarks/>
        Any,

        /// <remarks/>
        Email,

        /// <remarks/>
        Fax,

        /// <remarks/>
        Phone,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum ContactPreferenceTypePreferredContactTime
    {

        /// <remarks/>
        Anytime,

        /// <remarks/>
        Morning,

        /// <remarks/>
        Afternoon,

        /// <remarks/>
        Evening,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ApplicantType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string firstNameField;

        private string middleNameField;

        private string lastNameField;

        private NameSuffixType nameSuffixField;

        private bool nameSuffixFieldSpecified;

        private string streetField;

        private string cityField;

        private string countyField;

        private StateType stateField;

        private bool stateFieldSpecified;

        private string zipField;

        private string dateOfBirthField;

        private string homePhoneField;

        private string mobilePhoneField;

        private string workPhoneField;

        private int workPhoneExtField;

        private bool workPhoneExtFieldSpecified;

        private string emailAddressField;

        private string passwordField;

        private string sSNField;

        private YesNoType isVeteranField;

        private MaritalStatusType maritalStatusField;

        private bool maritalStatusFieldSpecified;

        private CitizenshipStatusType isUSCitizenField;

        private bool isUSCitizenFieldSpecified;

        private RelationshipToApplicantType relationshipToApplicantField;

        private bool relationshipToApplicantFieldSpecified;

        private ContactPreferenceType contactPreferenceField;

        private EmploymentType employmentField;

        private CreditHistoryType creditHistoryField;

        private ApplicantTypePrimary primaryField;

        private ApplicantTypePrimaryContact primaryContactField;

        public ApplicantType()
        {
            this.isVeteranField = YesNoType.N;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
        public string MiddleName
        {
            get
            {
                return this.middleNameField;
            }
            set
            {
                this.middleNameField = value;
                this.RaisePropertyChanged("MiddleName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
        public string LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }

        /// <remarks/>
        public NameSuffixType NameSuffix
        {
            get
            {
                return this.nameSuffixField;
            }
            set
            {
                this.nameSuffixField = value;
                this.RaisePropertyChanged("NameSuffix");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NameSuffixSpecified
        {
            get
            {
                return this.nameSuffixFieldSpecified;
            }
            set
            {
                this.nameSuffixFieldSpecified = value;
                this.RaisePropertyChanged("NameSuffixSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
        public string Street
        {
            get
            {
                return this.streetField;
            }
            set
            {
                this.streetField = value;
                this.RaisePropertyChanged("Street");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
        public string County
        {
            get
            {
                return this.countyField;
            }
            set
            {
                this.countyField = value;
                this.RaisePropertyChanged("County");
            }
        }

        /// <remarks/>
        public StateType State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
                this.stateFieldSpecified = true;
                this.RaisePropertyChanged("State");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StateSpecified
        {
            get
            {
                return this.stateFieldSpecified;
            }
            set
            {
                this.stateFieldSpecified = value;
                this.RaisePropertyChanged("StateSpecified");
            }
        }

        /// <remarks/>
        public string Zip
        {
            get
            {
                return this.zipField;
            }
            set
            {
                this.zipField = value;
                this.RaisePropertyChanged("Zip");
            }
        }

        /// <remarks/>
        public string DateOfBirth
        {
            get
            {
                return this.dateOfBirthField;
            }
            set
            {
                this.dateOfBirthField = value;
                this.RaisePropertyChanged("DateOfBirth");
            }
        }

        /// <remarks/>
        public string HomePhone
        {
            get
            {
                return this.homePhoneField;
            }
            set
            {
                this.homePhoneField = value;
                this.RaisePropertyChanged("HomePhone");
            }
        }

        /// <remarks/>
        public string MobilePhone
        {
            get
            {
                return this.mobilePhoneField;
            }
            set
            {
                this.mobilePhoneField = value;
                this.RaisePropertyChanged("MobilePhone");
            }
        }

        /// <remarks/>
        public string WorkPhone
        {
            get
            {
                return this.workPhoneField;
            }
            set
            {
                this.workPhoneField = value;
                this.RaisePropertyChanged("WorkPhone");
            }
        }

        /// <remarks/>
        public int WorkPhoneExt
        {
            get
            {
                return this.workPhoneExtField;
            }
            set
            {
                this.workPhoneExtField = value;
                this.RaisePropertyChanged("WorkPhoneExt");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WorkPhoneExtSpecified
        {
            get
            {
                return this.workPhoneExtFieldSpecified;
            }
            set
            {
                this.workPhoneExtFieldSpecified = value;
                this.RaisePropertyChanged("WorkPhoneExtSpecified");
            }
        }

        /// <remarks/>
        public string EmailAddress
        {
            get
            {
                return this.emailAddressField;
            }
            set
            {
                this.emailAddressField = value;
                this.RaisePropertyChanged("EmailAddress");
            }
        }

        /// <remarks/>
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }

        /// <remarks/>
        public string SSN
        {
            get
            {
                return this.sSNField;
            }
            set
            {
                this.sSNField = value;
                this.RaisePropertyChanged("SSN");
            }
        }

        /// <remarks/>
        public YesNoType IsVeteran
        {
            get
            {
                return this.isVeteranField;
            }
            set
            {
                this.isVeteranField = value;
                this.RaisePropertyChanged("IsVeteran");
            }
        }

        /// <remarks/>
        public MaritalStatusType MaritalStatus
        {
            get
            {
                return this.maritalStatusField;
            }
            set
            {
                this.maritalStatusField = value;
                this.RaisePropertyChanged("MaritalStatus");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaritalStatusSpecified
        {
            get
            {
                return this.maritalStatusFieldSpecified;
            }
            set
            {
                this.maritalStatusFieldSpecified = value;
                this.RaisePropertyChanged("MaritalStatusSpecified");
            }
        }

        /// <remarks/>
        public CitizenshipStatusType IsUSCitizen
        {
            get
            {
                return this.isUSCitizenField;
            }
            set
            {
                this.isUSCitizenField = value;
                this.RaisePropertyChanged("IsUSCitizen");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsUSCitizenSpecified
        {
            get
            {
                return this.isUSCitizenFieldSpecified;
            }
            set
            {
                this.isUSCitizenFieldSpecified = value;
                this.RaisePropertyChanged("IsUSCitizenSpecified");
            }
        }

        /// <remarks/>
        public RelationshipToApplicantType RelationshipToApplicant
        {
            get
            {
                return this.relationshipToApplicantField;
            }
            set
            {
                this.relationshipToApplicantField = value;
                this.RaisePropertyChanged("RelationshipToApplicant");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RelationshipToApplicantSpecified
        {
            get
            {
                return this.relationshipToApplicantFieldSpecified;
            }
            set
            {
                this.relationshipToApplicantFieldSpecified = value;
                this.RaisePropertyChanged("RelationshipToApplicantSpecified");
            }
        }

        /// <remarks/>
        public ContactPreferenceType ContactPreference
        {
            get
            {
                return this.contactPreferenceField;
            }
            set
            {
                this.contactPreferenceField = value;
                this.RaisePropertyChanged("ContactPreference");
            }
        }

        /// <remarks/>
        public EmploymentType Employment
        {
            get
            {
                return this.employmentField;
            }
            set
            {
                this.employmentField = value;
                this.RaisePropertyChanged("Employment");
            }
        }

        /// <remarks/>
        public CreditHistoryType CreditHistory
        {
            get
            {
                if (creditHistoryField == null)
                    creditHistoryField = new CreditHistoryType();

                return this.creditHistoryField;
            }
            set
            {
                this.creditHistoryField = value;
                this.RaisePropertyChanged("CreditHistory");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public ApplicantTypePrimary Primary
        {
            get
            {
                return this.primaryField;
            }
            set
            {
                this.primaryField = value;
                this.RaisePropertyChanged("Primary");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public ApplicantTypePrimaryContact PrimaryContact
        {
            get
            {
                return this.primaryContactField;
            }
            set
            {
                this.primaryContactField = value;
                this.RaisePropertyChanged("PrimaryContact");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum NameSuffixType
    {

        /// <remarks/>
        I,

        /// <remarks/>
        II,

        /// <remarks/>
        III,

        /// <remarks/>
        IV,

        /// <remarks/>
        JR,

        /// <remarks/>
        SR,

        /// <remarks/>
        V,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum StateType
    {

        /// <remarks/>
        AK,

        /// <remarks/>
        AL,

        /// <remarks/>
        AR,

        /// <remarks/>
        AZ,

        /// <remarks/>
        CA,

        /// <remarks/>
        CO,

        /// <remarks/>
        CT,

        /// <remarks/>
        DE,

        /// <remarks/>
        DC,

        /// <remarks/>
        FL,

        /// <remarks/>
        GA,

        /// <remarks/>
        HI,

        /// <remarks/>
        ID,

        /// <remarks/>
        IL,

        /// <remarks/>
        IN,

        /// <remarks/>
        IA,

        /// <remarks/>
        KS,

        /// <remarks/>
        KY,

        /// <remarks/>
        LA,

        /// <remarks/>
        ME,

        /// <remarks/>
        MD,

        /// <remarks/>
        MA,

        /// <remarks/>
        MI,

        /// <remarks/>
        MN,

        /// <remarks/>
        MS,

        /// <remarks/>
        MO,

        /// <remarks/>
        MT,

        /// <remarks/>
        NE,

        /// <remarks/>
        NV,

        /// <remarks/>
        NH,

        /// <remarks/>
        NJ,

        /// <remarks/>
        NM,

        /// <remarks/>
        NY,

        /// <remarks/>
        NC,

        /// <remarks/>
        ND,

        /// <remarks/>
        OH,

        /// <remarks/>
        OK,

        /// <remarks/>
        OR,

        /// <remarks/>
        PA,

        /// <remarks/>
        RI,

        /// <remarks/>
        SC,

        /// <remarks/>
        SD,

        /// <remarks/>
        TN,

        /// <remarks/>
        TX,

        /// <remarks/>
        UT,

        /// <remarks/>
        VT,

        /// <remarks/>
        VA,

        /// <remarks/>
        WA,

        /// <remarks/>
        WV,

        /// <remarks/>
        WI,

        /// <remarks/>
        WY,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum MaritalStatusType
    {

        /// <remarks/>
        MARRIED,

        /// <remarks/>
        UNMARRIED,

        /// <remarks/>
        SEPARATED,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum CitizenshipStatusType
    {

        /// <remarks/>
        NONPERMANENTRESIDENTALIEN,

        /// <remarks/>
        NONRESIDENTALIEN,

        /// <remarks/>
        PERMANENTRESIDENTALIEN,

        /// <remarks/>
        USCITIZEN,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum RelationshipToApplicantType
    {

        /// <remarks/>
        SPOUSE,

        /// <remarks/>
        PARENT,

        /// <remarks/>
        SELF,

        /// <remarks/>
        OTHER,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum ApplicantTypePrimary
    {

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum ApplicantTypePrimaryContact
    {

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HomeEquitySubjectPropertyType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private PropertyType propertyTypeField;

        private PropertyUseType propertyUseField;

        private string propertyAddressField;

        private StateType propertyStateField;

        private bool propertyStateFieldSpecified;

        private string propertyCountyField;

        private string propertyCityField;

        private string propertyZipField;

        private UnitsType unitsField;

        private bool unitsFieldSpecified;

        public HomeEquitySubjectPropertyType()
        {
            this.propertyTypeField = PropertyType.SINGLEFAMDET;
            this.propertyUseField = PropertyUseType.OWNEROCCUPIED;
        }

        /// <remarks/>
        public PropertyType PropertyType
        {
            get
            {
                return this.propertyTypeField;
            }
            set
            {
                this.propertyTypeField = value;
                this.RaisePropertyChanged("PropertyType");
            }
        }

        /// <remarks/>
        public PropertyUseType PropertyUse
        {
            get
            {
                return this.propertyUseField;
            }
            set
            {
                this.propertyUseField = value;
                this.RaisePropertyChanged("PropertyUse");
            }
        }

        /// <remarks/>
        public string PropertyAddress
        {
            get
            {
                return this.propertyAddressField;
            }
            set
            {
                this.propertyAddressField = value;
                this.RaisePropertyChanged("PropertyAddress");
            }
        }

        /// <remarks/>
        public StateType PropertyState
        {
            get
            {
                return this.propertyStateField;
            }
            set
            {
                this.propertyStateField = value;
                this.RaisePropertyChanged("PropertyState");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PropertyStateSpecified
        {
            get
            {
                return this.propertyStateFieldSpecified;
            }
            set
            {
                this.propertyStateFieldSpecified = value;
                this.RaisePropertyChanged("PropertyStateSpecified");
            }
        }

        /// <remarks/>
        public string PropertyCounty
        {
            get
            {
                return this.propertyCountyField;
            }
            set
            {
                this.propertyCountyField = value;
                this.RaisePropertyChanged("PropertyCounty");
            }
        }

        /// <remarks/>
        public string PropertyCity
        {
            get
            {
                return this.propertyCityField;
            }
            set
            {
                this.propertyCityField = value;
                this.RaisePropertyChanged("PropertyCity");
            }
        }

        /// <remarks/>
        public string PropertyZip
        {
            get
            {
                return this.propertyZipField;
            }
            set
            {
                this.propertyZipField = value;
                this.RaisePropertyChanged("PropertyZip");
            }
        }

        /// <remarks/>
        public UnitsType Units
        {
            get
            {
                return this.unitsField;
            }
            set
            {
                this.unitsField = value;
                this.RaisePropertyChanged("Units");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UnitsSpecified
        {
            get
            {
                return this.unitsFieldSpecified;
            }
            set
            {
                this.unitsFieldSpecified = value;
                this.RaisePropertyChanged("UnitsSpecified");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum PropertyType
    {

        /// <remarks/>
        SINGLEFAMDET,

        /// <remarks/>
        SINGLEFAMATT,

        /// <remarks/>
        LOWRISECONDO,

        /// <remarks/>
        HIGHRISECONDO,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2TO4UNITFAM")]
        Item2TO4UNITFAM,

        /// <remarks/>
        COOP,

        /// <remarks/>
        MODULAR,

        /// <remarks/>
        MOBILEPERMANENT,

        /// <remarks/>
        MOBILEMOVEABLE,

        /// <remarks/>
        MANUFACTURED,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum PropertyUseType
    {

        /// <remarks/>
        OWNEROCCUPIED,

        /// <remarks/>
        SECONDHOME,

        /// <remarks/>
        INVESTMENTPROPERTY,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum UnitsType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1UNIT")]
        Item1UNIT,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2UNITS")]
        Item2UNITS,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3UNITS")]
        Item3UNITS,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4UNITS")]
        Item4UNITS,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5ORMOREUNITS")]
        Item5ORMOREUNITS,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HomeEquityType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private YesNoType firstHomeField;

        private bool firstHomeFieldSpecified;

        private decimal propertyEstimatedValueField;

        private decimal monthlyPaymentField;

        private bool monthlyPaymentFieldSpecified;

        private decimal cashOutField;

        private ProductType[] requestedProductsField;

        private HomeEquityPurposesType[] homeEquityPurposeField;

        private HomeEquitySubjectPropertyType subjectPropertyField;

        /// <remarks/>
        public YesNoType FirstHome
        {
            get
            {
                return this.firstHomeField;
            }
            set
            {
                this.firstHomeField = value;
                this.RaisePropertyChanged("FirstHome");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FirstHomeSpecified
        {
            get
            {
                return this.firstHomeFieldSpecified;
            }
            set
            {
                this.firstHomeFieldSpecified = value;
                this.RaisePropertyChanged("FirstHomeSpecified");
            }
        }

        /// <remarks/>
        public decimal PropertyEstimatedValue
        {
            get
            {
                return this.propertyEstimatedValueField;
            }
            set
            {
                this.propertyEstimatedValueField = value;
                this.RaisePropertyChanged("PropertyEstimatedValue");
            }
        }

        /// <remarks/>
        public decimal MonthlyPayment
        {
            get
            {
                return this.monthlyPaymentField;
            }
            set
            {
                this.monthlyPaymentField = value;
                this.RaisePropertyChanged("MonthlyPayment");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MonthlyPaymentSpecified
        {
            get
            {
                return this.monthlyPaymentFieldSpecified;
            }
            set
            {
                this.monthlyPaymentFieldSpecified = value;
                this.RaisePropertyChanged("MonthlyPaymentSpecified");
            }
        }

        /// <remarks/>
        public decimal CashOut
        {
            get
            {
                return this.cashOutField;
            }
            set
            {
                this.cashOutField = value;
                this.RaisePropertyChanged("CashOut");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Product", IsNullable = false)]
        public ProductType[] RequestedProducts
        {
            get
            {
                return this.requestedProductsField;
            }
            set
            {
                this.requestedProductsField = value;
                this.RaisePropertyChanged("RequestedProducts");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Purpose", IsNullable = false)]
        public HomeEquityPurposesType[] HomeEquityPurpose
        {
            get
            {
                return this.homeEquityPurposeField;
            }
            set
            {
                this.homeEquityPurposeField = value;
                this.RaisePropertyChanged("HomeEquityPurpose");
            }
        }

        /// <remarks/>
        public HomeEquitySubjectPropertyType SubjectProperty
        {
            get
            {
                return this.subjectPropertyField;
            }
            set
            {
                this.subjectPropertyField = value;
                this.RaisePropertyChanged("SubjectProperty");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum ProductType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5YRFHELOAN")]
        Item5YRFHELOAN,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5YRVHELOAN")]
        Item5YRVHELOAN,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5YRFHELOC")]
        Item5YRFHELOC,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5YRVHELOC")]
        Item5YRVHELOC,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7YRFHELOAN")]
        Item7YRFHELOAN,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7YRVHELOAN")]
        Item7YRVHELOAN,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7YRFHELOC")]
        Item7YRFHELOC,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7YRVHELOC")]
        Item7YRVHELOC,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10YRFHELOAN")]
        Item10YRFHELOAN,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10YRVHELOAN")]
        Item10YRVHELOAN,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10YRFHELOC")]
        Item10YRFHELOC,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10YRVHELOC")]
        Item10YRVHELOC,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("15YRFHELOAN")]
        Item15YRFHELOAN,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("15YRVHELOAN")]
        Item15YRVHELOAN,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("15YRFHELOC")]
        Item15YRFHELOC,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("15YRVHELOC")]
        Item15YRVHELOC,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20YRFHELOAN")]
        Item20YRFHELOAN,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20YRVHELOAN")]
        Item20YRVHELOAN,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20YRFHELOC")]
        Item20YRFHELOC,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20YRVHELOC")]
        Item20YRVHELOC,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("25YRFHELOAN")]
        Item25YRFHELOAN,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("25YRVHELOAN")]
        Item25YRVHELOAN,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("25YRFHELOC")]
        Item25YRFHELOC,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("25YRVHELOC")]
        Item25YRVHELOC,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("30YRFHELOAN")]
        Item30YRFHELOAN,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("30YRVHELOAN")]
        Item30YRVHELOAN,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("30YRFHELOC")]
        Item30YRFHELOC,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("30YRVHELOC")]
        Item30YRVHELOC,

        /// <remarks/>
        OTHERINNOVATIVEHEPRODUCTS,

        /// <remarks/>
        MORTGAGEOTHER,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10YRF")]
        Item10YRF,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("15YRF")]
        Item15YRF,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20YRF")]
        Item20YRF,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("25YRF")]
        Item25YRF,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("30YRF")]
        Item30YRF,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("40YRF")]
        Item40YRF,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5YRB")]
        Item5YRB,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7YRB")]
        Item7YRB,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10YRB")]
        Item10YRB,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6MONTHARM")]
        Item6MONTHARM,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1YRARM")]
        Item1YRARM,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2YRARM")]
        Item2YRARM,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3YRARM")]
        Item3YRARM,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5YRARM")]
        Item5YRARM,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7YRARM")]
        Item7YRARM,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10YRARM")]
        Item10YRARM,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5YRARM-INTONLY")]
        Item5YRARMINTONLY,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10YRARM-INTONLY")]
        Item10YRARMINTONLY,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("15YRARM-INTONLY")]
        Item15YRARMINTONLY,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20YRARM-INTONLY")]
        Item20YRARMINTONLY,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("25YRARM-INTONLY")]
        Item25YRARMINTONLY,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("30YRARM-INTONLY")]
        Item30YRARMINTONLY,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum HomeEquityPurposesType
    {

        /// <remarks/>
        PAYOFFHELOAN,

        /// <remarks/>
        PAYOFFHELOC,

        /// <remarks/>
        HOMEIMP,

        /// <remarks/>
        DEBTCONSOLIDATION,

        /// <remarks/>
        AUTOPURCHASE,

        /// <remarks/>
        BOATPURCHASE,

        /// <remarks/>
        RVPURCHASE,

        /// <remarks/>
        MOTORCYCLEPURCHASE,

        /// <remarks/>
        OTHER,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RefinanceSubjectPropertyType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private PropertyType propertyTypeField;

        private PropertyUseType propertyUseField;

        private string propertyAddressField;

        private StateType propertyStateField;

        private bool propertyStateFieldSpecified;

        private string propertyCountyField;

        private string propertyCityField;

        private string propertyZipField;

        private UnitsType unitsField;

        private bool unitsFieldSpecified;

        public RefinanceSubjectPropertyType()
        {
            this.propertyTypeField = PropertyType.SINGLEFAMDET;
            this.propertyUseField = PropertyUseType.OWNEROCCUPIED;
        }

        /// <remarks/>
        public PropertyType PropertyType
        {
            get
            {
                return this.propertyTypeField;
            }
            set
            {
                this.propertyTypeField = value;
                this.RaisePropertyChanged("PropertyType");
            }
        }

        /// <remarks/>
        public PropertyUseType PropertyUse
        {
            get
            {
                return this.propertyUseField;
            }
            set
            {
                this.propertyUseField = value;
                this.RaisePropertyChanged("PropertyUse");
            }
        }

        /// <remarks/>
        public string PropertyAddress
        {
            get
            {
                return this.propertyAddressField;
            }
            set
            {
                this.propertyAddressField = value;
                this.RaisePropertyChanged("PropertyAddress");
            }
        }

        /// <remarks/>
        public StateType PropertyState
        {
            get
            {
                return this.propertyStateField;
            }
            set
            {
                this.propertyStateField = value;
                this.RaisePropertyChanged("PropertyState");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PropertyStateSpecified
        {
            get
            {
                return this.propertyStateFieldSpecified;
            }
            set
            {
                this.propertyStateFieldSpecified = value;
                this.RaisePropertyChanged("PropertyStateSpecified");
            }
        }

        /// <remarks/>
        public string PropertyCounty
        {
            get
            {
                return this.propertyCountyField;
            }
            set
            {
                this.propertyCountyField = value;
                this.RaisePropertyChanged("PropertyCounty");
            }
        }

        /// <remarks/>
        public string PropertyCity
        {
            get
            {
                return this.propertyCityField;
            }
            set
            {
                this.propertyCityField = value;
                this.RaisePropertyChanged("PropertyCity");
            }
        }

        /// <remarks/>
        public string PropertyZip
        {
            get
            {
                return this.propertyZipField;
            }
            set
            {
                this.propertyZipField = value;
                this.RaisePropertyChanged("PropertyZip");
            }
        }

        /// <remarks/>
        public UnitsType Units
        {
            get
            {
                return this.unitsField;
            }
            set
            {
                this.unitsField = value;
                this.RaisePropertyChanged("Units");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UnitsSpecified
        {
            get
            {
                return this.unitsFieldSpecified;
            }
            set
            {
                this.unitsFieldSpecified = value;
                this.RaisePropertyChanged("UnitsSpecified");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RefinanceType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private decimal requestedLoanAmountField;

        private bool requestedLoanAmountFieldSpecified;

        private decimal propertyEstimatedValueField;

        private decimal monthlyPaymentField;

        private decimal estimatedMortgageBalanceField;

        private decimal firstMortgageInterestRateField;

        private bool firstMortgageInterestRateFieldSpecified;

        private YesNoType haveMultipleMortagesField;

        private decimal secondMortgageBalanceField;

        private bool secondMortgageBalanceFieldSpecified;

        private decimal secondMortgageMonthlyPaymentField;

        private bool secondMortgageMonthlyPaymentFieldSpecified;

        private decimal secondMortgageInterestRateField;

        private bool secondMortgageInterestRateFieldSpecified;

        private ProductType[] requestedProductsField;

        private RefinancePurposesType[] refinancePurposeField;

        private decimal cashOutField;

        private RefinanceSubjectPropertyType subjectPropertyField;

        public RefinanceType()
        {
            this.haveMultipleMortagesField = YesNoType.N;
            this.cashOutField = ((decimal)(0m));
        }

        /// <remarks/>
        public decimal RequestedLoanAmount
        {
            get
            {
                return this.requestedLoanAmountField;
            }
            set
            {
                this.requestedLoanAmountField = value;
                this.RaisePropertyChanged("RequestedLoanAmount");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RequestedLoanAmountSpecified
        {
            get
            {
                return this.requestedLoanAmountFieldSpecified;
            }
            set
            {
                this.requestedLoanAmountFieldSpecified = value;
                this.RaisePropertyChanged("RequestedLoanAmountSpecified");
            }
        }

        /// <remarks/>
        public decimal PropertyEstimatedValue
        {
            get
            {
                return this.propertyEstimatedValueField;
            }
            set
            {
                this.propertyEstimatedValueField = value;
                this.RaisePropertyChanged("PropertyEstimatedValue");
            }
        }

        /// <remarks/>
        public decimal MonthlyPayment
        {
            get
            {
                return this.monthlyPaymentField;
            }
            set
            {
                this.monthlyPaymentField = value;
                this.RaisePropertyChanged("MonthlyPayment");
            }
        }

        /// <remarks/>
        public decimal EstimatedMortgageBalance
        {
            get
            {
                return this.estimatedMortgageBalanceField;
            }
            set
            {
                this.estimatedMortgageBalanceField = value;
                this.RaisePropertyChanged("EstimatedMortgageBalance");
            }
        }

        /// <remarks/>
        public decimal FirstMortgageInterestRate
        {
            get
            {
                return this.firstMortgageInterestRateField;
            }
            set
            {
                this.firstMortgageInterestRateField = value;
                this.RaisePropertyChanged("FirstMortgageInterestRate");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FirstMortgageInterestRateSpecified
        {
            get
            {
                return this.firstMortgageInterestRateFieldSpecified;
            }
            set
            {
                this.firstMortgageInterestRateFieldSpecified = value;
                this.RaisePropertyChanged("FirstMortgageInterestRateSpecified");
            }
        }

        /// <remarks/>
        public YesNoType HaveMultipleMortages
        {
            get
            {
                return this.haveMultipleMortagesField;
            }
            set
            {
                this.haveMultipleMortagesField = value;
                this.RaisePropertyChanged("HaveMultipleMortages");
            }
        }

        /// <remarks/>
        public decimal SecondMortgageBalance
        {
            get
            {
                return this.secondMortgageBalanceField;
            }
            set
            {
                this.secondMortgageBalanceField = value;
                this.RaisePropertyChanged("SecondMortgageBalance");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SecondMortgageBalanceSpecified
        {
            get
            {
                return this.secondMortgageBalanceFieldSpecified;
            }
            set
            {
                this.secondMortgageBalanceFieldSpecified = value;
                this.RaisePropertyChanged("SecondMortgageBalanceSpecified");
            }
        }

        /// <remarks/>
        public decimal SecondMortgageMonthlyPayment
        {
            get
            {
                return this.secondMortgageMonthlyPaymentField;
            }
            set
            {
                this.secondMortgageMonthlyPaymentField = value;
                this.RaisePropertyChanged("SecondMortgageMonthlyPayment");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SecondMortgageMonthlyPaymentSpecified
        {
            get
            {
                return this.secondMortgageMonthlyPaymentFieldSpecified;
            }
            set
            {
                this.secondMortgageMonthlyPaymentFieldSpecified = value;
                this.RaisePropertyChanged("SecondMortgageMonthlyPaymentSpecified");
            }
        }

        /// <remarks/>
        public decimal SecondMortgageInterestRate
        {
            get
            {
                return this.secondMortgageInterestRateField;
            }
            set
            {
                this.secondMortgageInterestRateField = value;
                this.RaisePropertyChanged("SecondMortgageInterestRate");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SecondMortgageInterestRateSpecified
        {
            get
            {
                return this.secondMortgageInterestRateFieldSpecified;
            }
            set
            {
                this.secondMortgageInterestRateFieldSpecified = value;
                this.RaisePropertyChanged("SecondMortgageInterestRateSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Product", IsNullable = false)]
        public ProductType[] RequestedProducts
        {
            get
            {
                return this.requestedProductsField;
            }
            set
            {
                this.requestedProductsField = value;
                this.RaisePropertyChanged("RequestedProducts");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Purpose", IsNullable = false)]
        public RefinancePurposesType[] RefinancePurpose
        {
            get
            {
                return this.refinancePurposeField;
            }
            set
            {
                this.refinancePurposeField = value;
                this.RaisePropertyChanged("RefinancePurpose");
            }
        }

        /// <remarks/>
        public decimal CashOut
        {
            get
            {
                return this.cashOutField;
            }
            set
            {
                this.cashOutField = value;
                this.RaisePropertyChanged("CashOut");
            }
        }

        /// <remarks/>
        public RefinanceSubjectPropertyType SubjectProperty
        {
            get
            {
                if (this.subjectPropertyField == null) this.subjectPropertyField = new RefinanceSubjectPropertyType();
                return this.subjectPropertyField;
            }
            set
            {
                this.subjectPropertyField = value;
                this.RaisePropertyChanged("SubjectProperty");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum RefinancePurposesType
    {

        /// <remarks/>
        REFIPRIMARY,

        /// <remarks/>
        PAYOFFSECOND,

        /// <remarks/>
        PAYOFFHELOC,

        /// <remarks/>
        CASHOUT,

        /// <remarks/>
        PAYOFFSPOUSE,

        /// <remarks/>
        HOMEIMP,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PurchaseSubjectPropertyType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private PropertyType propertyTypeField;

        private PropertyUseType propertyUseField;

        private string propertyAddressField;

        private StateType propertyStateField;

        private string propertyCountyField;

        private string propertyCityField;

        private string propertyZipField;

        private UnitsType unitsField;

        private bool unitsFieldSpecified;

        public PurchaseSubjectPropertyType()
        {
            this.propertyTypeField = PropertyType.SINGLEFAMDET;
            this.propertyUseField = PropertyUseType.OWNEROCCUPIED;
        }

        /// <remarks/>
        public PropertyType PropertyType
        {
            get
            {
                return this.propertyTypeField;
            }
            set
            {
                this.propertyTypeField = value;
                this.RaisePropertyChanged("PropertyType");
            }
        }

        /// <remarks/>
        public PropertyUseType PropertyUse
        {
            get
            {
                return this.propertyUseField;
            }
            set
            {
                this.propertyUseField = value;
                this.RaisePropertyChanged("PropertyUse");
            }
        }

        /// <remarks/>
        public string PropertyAddress
        {
            get
            {
                return this.propertyAddressField;
            }
            set
            {
                this.propertyAddressField = value;
                this.RaisePropertyChanged("PropertyAddress");
            }
        }

        /// <remarks/>
        public StateType PropertyState
        {
            get
            {
                return this.propertyStateField;
            }
            set
            {
                this.propertyStateField = value;
                this.RaisePropertyChanged("PropertyState");
            }
        }

        /// <remarks/>
        public string PropertyCounty
        {
            get
            {
                return this.propertyCountyField;
            }
            set
            {
                this.propertyCountyField = value;
                this.RaisePropertyChanged("PropertyCounty");
            }
        }

        /// <remarks/>
        public string PropertyCity
        {
            get
            {
                return this.propertyCityField;
            }
            set
            {
                this.propertyCityField = value;
                this.RaisePropertyChanged("PropertyCity");
            }
        }

        /// <remarks/>
        public string PropertyZip
        {
            get
            {
                return this.propertyZipField;
            }
            set
            {
                this.propertyZipField = value;
                this.RaisePropertyChanged("PropertyZip");
            }
        }

        /// <remarks/>
        public UnitsType Units
        {
            get
            {
                return this.unitsField;
            }
            set
            {
                this.unitsField = value;
                this.RaisePropertyChanged("Units");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UnitsSpecified
        {
            get
            {
                return this.unitsFieldSpecified;
            }
            set
            {
                this.unitsFieldSpecified = value;
                this.RaisePropertyChanged("UnitsSpecified");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PurchaseType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private decimal requestedLoanAmountField;

        private bool requestedLoanAmountFieldSpecified;

        private decimal propertyPurchasePriceField;

        private YesNoType firstTimeHomeBuyerField;

        private bool firstTimeHomeBuyerFieldSpecified;

        private YesNoType foundAHomeField;

        private YesNoType signedSalesContractField;

        private bool signedSalesContractFieldSpecified;

        private YesNoType needRealtorField;

        private decimal downPaymentField;

        private ProductType[] requestedProductsField;

        private PurchaseSubjectPropertyType subjectPropertyField;

        public PurchaseType()
        {
            this.needRealtorField = YesNoType.Y;
        }

        /// <remarks/>
        public decimal RequestedLoanAmount
        {
            get
            {
                return this.requestedLoanAmountField;
            }
            set
            {
                this.requestedLoanAmountField = value;
                this.RaisePropertyChanged("RequestedLoanAmount");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RequestedLoanAmountSpecified
        {
            get
            {
                return this.requestedLoanAmountFieldSpecified;
            }
            set
            {
                this.requestedLoanAmountFieldSpecified = value;
                this.RaisePropertyChanged("RequestedLoanAmountSpecified");
            }
        }

        /// <remarks/>
        public decimal PropertyPurchasePrice
        {
            get
            {
                return this.propertyPurchasePriceField;
            }
            set
            {
                this.propertyPurchasePriceField = value;
                this.RaisePropertyChanged("PropertyPurchasePrice");
            }
        }

        /// <remarks/>
        public YesNoType FirstTimeHomeBuyer
        {
            get
            {
                return this.firstTimeHomeBuyerField;
            }
            set
            {
                this.firstTimeHomeBuyerField = value;
                this.RaisePropertyChanged("FirstTimeHomeBuyer");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FirstTimeHomeBuyerSpecified
        {
            get
            {
                return this.firstTimeHomeBuyerFieldSpecified;
            }
            set
            {
                this.firstTimeHomeBuyerFieldSpecified = value;
                this.RaisePropertyChanged("FirstTimeHomeBuyerSpecified");
            }
        }

        /// <remarks/>
        public YesNoType FoundAHome
        {
            get
            {
                return this.foundAHomeField;
            }
            set
            {
                this.foundAHomeField = value;
                this.RaisePropertyChanged("FoundAHome");
            }
        }

        /// <remarks/>
        public YesNoType SignedSalesContract
        {
            get
            {
                return this.signedSalesContractField;
            }
            set
            {
                this.signedSalesContractField = value;
                this.RaisePropertyChanged("SignedSalesContract");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SignedSalesContractSpecified
        {
            get
            {
                return this.signedSalesContractFieldSpecified;
            }
            set
            {
                this.signedSalesContractFieldSpecified = value;
                this.RaisePropertyChanged("SignedSalesContractSpecified");
            }
        }

        /// <remarks/>
        public YesNoType NeedRealtor
        {
            get
            {
                return this.needRealtorField;
            }
            set
            {
                this.needRealtorField = value;
                this.RaisePropertyChanged("NeedRealtor");
            }
        }

        /// <remarks/>
        public decimal DownPayment
        {
            get
            {
                return this.downPaymentField;
            }
            set
            {
                this.downPaymentField = value;
                this.RaisePropertyChanged("DownPayment");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Product", IsNullable = false)]
        public ProductType[] RequestedProducts
        {
            get
            {
                return this.requestedProductsField;
            }
            set
            {
                this.requestedProductsField = value;
                this.RaisePropertyChanged("RequestedProducts");
            }
        }

        /// <remarks/>
        public PurchaseSubjectPropertyType SubjectProperty
        {
            get
            {
                if (this.subjectPropertyField == null) this.subjectPropertyField = new PurchaseSubjectPropertyType();
                return this.subjectPropertyField;
            }
            set
            {
                this.subjectPropertyField = value;
                this.RaisePropertyChanged("SubjectProperty");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HomeLoanProductType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("HomeEquity", typeof(HomeEquityType))]
        [System.Xml.Serialization.XmlElementAttribute("Purchase", typeof(PurchaseType))]
        [System.Xml.Serialization.XmlElementAttribute("Refinance", typeof(RefinanceType))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
