//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LendingTreeLib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SessionKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SessionKeys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LendingTreeLib.SessionKeys", typeof(SessionKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppID.
        /// </summary>
        public static string AppID {
            get {
                return ResourceManager.GetString("AppID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnablePage..
        /// </summary>
        public static string EnablePagePrefix {
            get {
                return ResourceManager.GetString("EnablePagePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PixelFireDone.
        /// </summary>
        public static string PixelFireDone {
            get {
                return ResourceManager.GetString("PixelFireDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PixelFireEnabled.
        /// </summary>
        public static string PixelFireEnabled {
            get {
                return ResourceManager.GetString("PixelFireEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PropertyStateName.
        /// </summary>
        public static string PropertyStateName {
            get {
                return ResourceManager.GetString("PropertyStateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LendingTree.QuickMatch..
        /// </summary>
        public static string QuickMatchPrefix {
            get {
                return ResourceManager.GetString("QuickMatchPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReferringCdNumber.
        /// </summary>
        public static string ReferringCdNumber {
            get {
                return ResourceManager.GetString("ReferringCdNumber", resourceCulture);
            }
        }
    }
}
