//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DirectAgentsModel", "UserSelectedDirectTrackCampaign", "DirectTrackCampaigns", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CampaignWikiWebApplication1.Models.DirectAgents.DirectTrackCampaign), "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CampaignWikiWebApplication1.Models.DirectAgents.User))]

#endregion

namespace CampaignWikiWebApplication1.Models.DirectAgents
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DirectAgentsModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DirectAgentsModelContainer object using the connection string found in the 'DirectAgentsModelContainer' section of the application configuration file.
        /// </summary>
        public DirectAgentsModelContainer() : base("name=DirectAgentsModelContainer", "DirectAgentsModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DirectAgentsModelContainer object.
        /// </summary>
        public DirectAgentsModelContainer(string connectionString) : base(connectionString, "DirectAgentsModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DirectAgentsModelContainer object.
        /// </summary>
        public DirectAgentsModelContainer(EntityConnection connection) : base(connection, "DirectAgentsModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DirectTrackCampaign> DirectTrackCampaigns
        {
            get
            {
                if ((_DirectTrackCampaigns == null))
                {
                    _DirectTrackCampaigns = base.CreateObjectSet<DirectTrackCampaign>("DirectTrackCampaigns");
                }
                return _DirectTrackCampaigns;
            }
        }
        private ObjectSet<DirectTrackCampaign> _DirectTrackCampaigns;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DirectTrackCampaignGroup> DirectTrackCampaignGroups
        {
            get
            {
                if ((_DirectTrackCampaignGroups == null))
                {
                    _DirectTrackCampaignGroups = base.CreateObjectSet<DirectTrackCampaignGroup>("DirectTrackCampaignGroups");
                }
                return _DirectTrackCampaignGroups;
            }
        }
        private ObjectSet<DirectTrackCampaignGroup> _DirectTrackCampaignGroups;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DirectTrackCampaigns EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDirectTrackCampaigns(DirectTrackCampaign directTrackCampaign)
        {
            base.AddObject("DirectTrackCampaigns", directTrackCampaign);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DirectTrackCampaignGroups EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDirectTrackCampaignGroups(DirectTrackCampaignGroup directTrackCampaignGroup)
        {
            base.AddObject("DirectTrackCampaignGroups", directTrackCampaignGroup);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DirectAgentsModel", Name="DirectTrackCampaign")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DirectTrackCampaign : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DirectTrackCampaign object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="campaignNumber">Initial value of the CampaignNumber property.</param>
        /// <param name="campaignName">Initial value of the CampaignName property.</param>
        /// <param name="directTrackResource_Id">Initial value of the DirectTrackResource_Id property.</param>
        public static DirectTrackCampaign CreateDirectTrackCampaign(global::System.Int32 id, global::System.Int32 campaignNumber, global::System.String campaignName, global::System.Int32 directTrackResource_Id)
        {
            DirectTrackCampaign directTrackCampaign = new DirectTrackCampaign();
            directTrackCampaign.Id = id;
            directTrackCampaign.CampaignNumber = campaignNumber;
            directTrackCampaign.CampaignName = campaignName;
            directTrackCampaign.DirectTrackResource_Id = directTrackResource_Id;
            return directTrackCampaign;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CampaignNumber
        {
            get
            {
                return _CampaignNumber;
            }
            set
            {
                OnCampaignNumberChanging(value);
                ReportPropertyChanging("CampaignNumber");
                _CampaignNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CampaignNumber");
                OnCampaignNumberChanged();
            }
        }
        private global::System.Int32 _CampaignNumber;
        partial void OnCampaignNumberChanging(global::System.Int32 value);
        partial void OnCampaignNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CampaignName
        {
            get
            {
                return _CampaignName;
            }
            set
            {
                OnCampaignNameChanging(value);
                ReportPropertyChanging("CampaignName");
                _CampaignName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CampaignName");
                OnCampaignNameChanged();
            }
        }
        private global::System.String _CampaignName;
        partial void OnCampaignNameChanging(global::System.String value);
        partial void OnCampaignNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Campaign_Id
        {
            get
            {
                return _Campaign_Id;
            }
            set
            {
                OnCampaign_IdChanging(value);
                ReportPropertyChanging("Campaign_Id");
                _Campaign_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Campaign_Id");
                OnCampaign_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _Campaign_Id;
        partial void OnCampaign_IdChanging(Nullable<global::System.Int32> value);
        partial void OnCampaign_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DirectTrackResource_Id
        {
            get
            {
                return _DirectTrackResource_Id;
            }
            set
            {
                OnDirectTrackResource_IdChanging(value);
                ReportPropertyChanging("DirectTrackResource_Id");
                _DirectTrackResource_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DirectTrackResource_Id");
                OnDirectTrackResource_IdChanged();
            }
        }
        private global::System.Int32 _DirectTrackResource_Id;
        partial void OnDirectTrackResource_IdChanging(global::System.Int32 value);
        partial void OnDirectTrackResource_IdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DirectAgentsModel", "UserSelectedDirectTrackCampaign", "Users")]
        public EntityCollection<User> Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<User>("DirectAgentsModel.UserSelectedDirectTrackCampaign", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<User>("DirectAgentsModel.UserSelectedDirectTrackCampaign", "Users", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DirectAgentsModel", Name="DirectTrackCampaignGroup")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DirectTrackCampaignGroup : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DirectTrackCampaignGroup object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="directTrackResource_Id">Initial value of the DirectTrackResource_Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static DirectTrackCampaignGroup CreateDirectTrackCampaignGroup(global::System.Int32 id, global::System.Int32 directTrackResource_Id, global::System.String name)
        {
            DirectTrackCampaignGroup directTrackCampaignGroup = new DirectTrackCampaignGroup();
            directTrackCampaignGroup.Id = id;
            directTrackCampaignGroup.DirectTrackResource_Id = directTrackResource_Id;
            directTrackCampaignGroup.Name = name;
            return directTrackCampaignGroup;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DirectTrackResource_Id
        {
            get
            {
                return _DirectTrackResource_Id;
            }
            set
            {
                OnDirectTrackResource_IdChanging(value);
                ReportPropertyChanging("DirectTrackResource_Id");
                _DirectTrackResource_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DirectTrackResource_Id");
                OnDirectTrackResource_IdChanged();
            }
        }
        private global::System.Int32 _DirectTrackResource_Id;
        partial void OnDirectTrackResource_IdChanging(global::System.Int32 value);
        partial void OnDirectTrackResource_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DirectAgentsModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static User CreateUser(global::System.Int32 id, global::System.String name)
        {
            User user = new User();
            user.Id = id;
            user.Name = name;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DirectAgentsModel", "UserSelectedDirectTrackCampaign", "DirectTrackCampaigns")]
        public EntityCollection<DirectTrackCampaign> DirectTrackCampaigns
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DirectTrackCampaign>("DirectAgentsModel.UserSelectedDirectTrackCampaign", "DirectTrackCampaigns");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DirectTrackCampaign>("DirectAgentsModel.UserSelectedDirectTrackCampaign", "DirectTrackCampaigns", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
